crystalcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('crystals/', views.crystals_index, name='index'),
    path('crystals/<int:crystal_id>/', views.crystals_detail, name='detail'),
    path('crystals/create/', views.CrystalCreate.as_view(), name='crystals_create'),
    path('crystals/<int:pk>/update/', views.CrystalUpdate.as_view(), name='crystals_update'),
    path('crystals/<int:pk>/delete/', views.CrystalDelete.as_view(), name='crystals_delete'),
    path('crystals/<int:crystal_id>/add_aquired/', views.add_aquired, name='add_aquired'),
    path('crystals/<int:crystal_id>/assoc_prop/<int:prop_id>/', views.assoc_prop, name='assoc_prop'),
    path('crystals/<int:crystal_id>/unassoc_prop/<int:prop_id>/', views.unassoc_prop, name='unassoc_prop'),
    path('props/', views.PropList.as_view(), name='props_index'),
    path('props/<int:pk>/', views.PropDetail.as_view(), name='props_detail'),
    path('props/create/', views.PropCreate.as_view(), name='props_create'),
    path('props/<int:pk>/update/', views.PropUpdate.as_view(), name='props_update'),
    path('props/<int:pk>/delete/', views.PropDelete.as_view(), name='props_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Prop(models.Model):
    property = models.CharField(max_length=50)
    
    def __str__(self):
        return self.property
    
    def get_absolute_url(self):
        return reverse("props_detail", kwargs={"pk": self.id})
    
class Crystal(models.Model):
    name = models.CharField(max_length=50)
    hardness = models.IntegerField()
    structure = models.CharField(max_length=50)
    color = models.CharField(max_length=100)
    transparency = models.CharField(max_length=50)
    props = models.ManyToManyField(Prop)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'crystal_id': self.id})
    
class Aquired(models.Model):
    date = models.DateField('Date Aquired')
    location = models.CharField(max_length=50)

    crystal = models.ForeignKey(Crystal, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.location} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Aquired

class AquiredForm(ModelForm):
    class Meta:
        model = Aquired
        fields = ['date', 'location']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Crystal, Prop
from .forms import AquiredForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def crystals_index(request):
    crystals = Crystal.objects.all()
    return render(request, 'crystals/index.html', {
        'crystals': crystals
    })

def crystals_detail(request, crystal_id):
    crystal = Crystal.objects.get(id=crystal_id)
    id_list = crystal.props.all().values_list('id')
    props_crystal_doesnt_have = Prop.objects.exclude(id__in=id_list)
    aquired_form = AquiredForm()
    return render(request, 'crystals/detail.html', {
        'crystal': crystal,
        'aquired_form': aquired_form,
        'props': props_crystal_doesnt_have
        })

class CrystalCreate(CreateView):
    model = Crystal
    fields = ['name', 'hardness', 'structure', 'color', 'transparency']

class CrystalUpdate(UpdateView):
    model = Crystal
    fields = ['hardness', 'structure', 'color', 'transparency']

class CrystalDelete(DeleteView):
    model = Crystal
    success_url = '/crystals'

def add_aquired(request, crystal_id):
    form = AquiredForm(request.POST)
    if form.is_valid():
        new_aquired = form.save(commit=False)
        new_aquired.crystal_id = crystal_id
        new_aquired.save()
    return redirect('detail', crystal_id=crystal_id)

class PropList(ListView):
  model = Prop

class PropDetail(DetailView):
  model = Prop

class PropCreate(CreateView):
  model = Prop
  fields = '__all__'

class PropUpdate(UpdateView):
  model = Prop
  fields = ['property']

class PropDelete(DeleteView):
  model = Prop
  success_url = '/props'

def assoc_prop(request, crystal_id, prop_id):
   Crystal.objects.get(id=crystal_id).props.add(prop_id)
   return redirect('detail', crystal_id=crystal_id)

def unassoc_prop(request, crystal_id, prop_id):
   Crystal.objects.get(id=crystal_id).props.remove(prop_id)
   return redirect('detail', crystal_id=crystal_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About the Crystal Collector</h1>
    <hr>
    <p>Hire the Crystal Collector!</p>
    <footer>All Rights Reserved, &copy; 2022 Crystal Collector</footer>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Crystal Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Crystal Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'props_create' %}">Add a Property</a></li>
          <li><a href="{% url 'props_index' %}">View All Properties</a></li>
          <li><a href="{% url 'crystals_create' %}">Add a Crystal</a></li>
          <li><a href="{% url 'index' %}">View All My Crystals</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Crystal Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/crystals/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Crystal Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ crystal.name }}</span>
        <p>Hardness: {{ crystal.hardness }}</p>
        <p>Crystal Structure: {{ crystal.structure|linebreaks }}</p>
        <p>Color: {{ crystal.color }}</p>
        <p>Transparency: {{ crystal.transparency }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'crystals_update' crystal.id %}">Edit</a>
        <a href="{% url 'crystals_delete' crystal.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_aquired' crystal.id %}" method="POST">
      {% csrf_token %}
      {{ aquired_form.as_p }}
      <input type="submit" class="btn" value="Add Location">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Location</th></tr>
      </thead>
      <tbody>
        {% for aquired in crystal.aquired_set.all %}
          <tr>
            <td>{{aquired.date}}</td>
            <td>{{aquired.location}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ crystal.name }}'s Properties</h3>
      {% if crystal.props.count %}
        {% for prop in crystal.props.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ prop.property }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'unassoc_prop' crystal.id prop.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Properties</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Properties</h3>
      {% if props.count %}
        {% for prop in props.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
               {{ prop.property }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_prop' crystal.id prop.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{crystal.property}} Already Has All Properties Available</h5>
      {% endif %}
    </div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });  
</script>  
{% endblock %}

main_app/templates/crystals/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Crystal List</h1>

{% for crystal in crystals %}
  <div class="card">
    <a href="{% url 'detail' crystal.id %}">
      <div class="card-content">
        <span class="card-title">{{ crystal.name }}</span>
        <p>Hardness: {{ crystal.hardness }}</p>
        <p>Structure: {{ crystal.structure }}</p>
        <p>Color: {{ crystal.color }}</p>
        <p>Transparency: {{ crystal.transparency }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Home</h1>
{% endblock %}

main_app/templates/main_app/crystal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' crystal.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/crystal_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add Crystal</h1>
{% endif %}  
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/prop_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Property Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ prop.property }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'props_update' prop.id %}">Edit</a>
        <a href="{% url 'props_delete' prop.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/prop_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Property</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/prop_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Property List</h1>

{% for prop in prop_list %}
  <a href="{% url 'props_detail' prop.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ prop.property }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}